name: publish-image

on:
  push:
    branches:
      - master

env:
  CARGO_TERM_COLOR: always
  SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Log in to the container registry
      run: make cr-login
      env:
        CR_PAT: ${{ secrets.CR_PAT }}

    - name: Test the backend
      run: make -C backend lint test

    - name: Test the frontend
      run: make -C frontend install lint test

    - name: Build the image
      run: make build-image

    - name: Publish the image
      run: make publish-image
