name: rust-test

on:
  push:
    branches-ignore:
      - master
    paths: 'backend/**'

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    # Adds cache with some defaults, see https://github.com/marketplace/actions/rust-cache
    - uses: Swatinem/rust-cache@v2

    - name: Run Clippy
      run: |
        cd backend
        cargo clippy
        cargo fmt --check

    - name: Run tests
      run: |
        cd backend
        cargo test --verbose
